language: python

python:
  - 3.6

services:
  - docker

install:
  - pip install -U codecov

script:
  - bash tests/test-with-compose.sh

after_success:
  - codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: isabl-io
  password: <TO REPLACE THIS RUN `travis encrypt --add deploy.password`>
  on:
    tags: false
    repo: isabl-io/isabl_cli
    python: 3.6
    branch: master
